<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CLI.Core\CLI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.0" />
    <PackageReference Include="Spectre.Console.Cli.Extensions.DependencyInjection" Version="0.16.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <Target Name="CopyPluginToShell" AfterTargets="Build">
    <PropertyGroup>
      <ShellModulesDir>$(SolutionDir)CLI.Shell\bin\$(Configuration)\$(TargetFramework)\modules\</ShellModulesDir>
    </PropertyGroup>

    <MakeDir Directories="$(ShellModulesDir)" Condition="!Exists('$(ShellModulesDir)')" />

    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ShellModulesDir)" />
  </Target>
</Project>
